#!/bin/bash
#cd /triton/ics/work/ilievsm1/for_triton/spin_gdy

for i in  0.3 0.5 0.7 0.9 1 3 5 7
do 

for j in 1 3 5 7 10 15 20
do
echo "submitting job $i$j"
cat >jobs_output/job-${i}-${j}.sbatch<<EOF
#!/bin/bash
#SBATCH   -p batch
#SBATCH  --time=3-15:00:00
#SBATCH  --mem-per-cpu=5000
#SBATCH -o jobs_output/job-"$i"-"$j".out

cd /triton/ics/work/ilievsm1/for_triton/spin_gdy/
module load matlab
matlab -nodesktop -nosplash -nojvm -r "run_SPINgreedy('100','0.8',$j,$i,'exp','onto')"
EOF

sbatch jobs_output/job-${i}-${j}.sbatch
sleep 1
done

done

